### ISSUE TITLE
The connect page could steal your password and 2:nd factor token.

### ISSUE THREAD

**Issue by hultqvist** [walty8/simple-gmail-notes.chrome#1]
I'm not saying that it does.

But

I click the "connect" link and get a popup with login.
In that window the address bar is hidden.

A few red flags occurr
- I can't verify that it is actually google.com I enter my email and password into.
- The 2:nd factor token it asks for is the OTP rather than the yubikey which I would do since the yubikey token can't be stolen using another domain.
- Since I'm already logged in into the browser I don't see why it would ask me to login even less why it would ask me for my email address.

**Comment by walty8** [comment]
hi,

First of all, thanks for your comment, pls find follow my replies:

1) I understand your concerns, the authentication page I used is this one (as u may find it from the source code):

https://developer.chrome.com/apps/identity#method-launchWebAuthFlow

It's the official API from google, and I don't know why they hide the address bar.
If you are not sure, you could check or the manifest file and you will find that the plugin could only access those google sites. Those sites not registered in the manifest are not accessible from the plugin.

2) I am not familiar with the yubikey, but as far as I remember the token generated from this way could only be used with this application (related with the private key and public key).

3) The token for gmail is different from the token for google drive. Btw this is only a browser side plugin, I don't think I could get the token from the current gmail session. 

One common approach is to use the credential of the chrome browser, but for my case, I often need to log in two gmail address in the same browser.  So I decided to use the oauth flow for the authentication (actually it's more complicated).
