### ISSUE TITLE
Abstract style not always showing up

### ISSUE THREAD

**Issue by allamedo** [walty8/simple-gmail-notes.chrome#2]
I have some mails with notes on my starred folder. 
When I load this page I just can see some of the notes "abstract style". They are always the same notes that are missing.
I tried reloading the page, editing the notes, removing them... and nothing changes.

Hopefully you can reproduce the error and try to fix it.

Thank you for your work.
![sin nombre](https://cloud.githubusercontent.com/assets/16788378/12464163/fa93fe7c-bfc7-11e5-9c8f-17197d535cf4.png)

**Comment by walty8** [comment]
hi,

for my knowledge, did the note appear in your Google Drive?  (you could find the page by clicking the magnifier icon above the note editor text area)

thanks

**Comment by allamedo** [comment]
Hello Walty, 

Thank you for replying to my issue.

Here is what I noticed in my Google Drive folder:

-The preview note that I can see on my starred list is in that folder.

-Some of the notes not appearing on my starred list ARE in that folder.

-Some of the notes not apprearing on my starred list ARE NOT in that GD folder, but I can see the note once I enter into the email itself.

-Some notes in the GD folder are just duplicates, with the same mail ID and subject. Some of these duplicates have been created even in the same day, hour and minute. Other have different creation dates.

I hope that helps.

**Comment by walty8** [comment]
hi,

the third case is really strange:

-Some of the notes not apprearing on my starred list ARE NOT in that GD
folder, but I can see the note once I enter into the email itself.

because I ONLY stored the notes in GD, and nowhere else.

_So, just to be 100% sure, have you ever deleted the notes from Google
drive?_

p.s. I know the duplicate sometimes happens, but I am not sure why it
happens (but it's likely to be related with network issues). but it should
not affect the usage, because I always show the last note in case of
repeat. I would try to fix that in the future.

thanks.

On Fri, Jan 22, 2016 at 11:04 PM, pundergit notifications@github.com
wrote:

> Hello Walty,
> 
> Thank you for replying to my issue.
> 
> Here is what I noticed in my Google Drive folder:
> 
> -The preview note that I can see on my starred list is in that folder.
> 
> -Some of the notes not appearing on my starred list ARE in that folder.
> 
> -Some of the notes not apprearing on my starred list ARE NOT in that GD
> folder, but I can see the note once I enter into the email itself.
> 
> -Some notes in the GD folder are just duplicates, with the same mail ID
> and subject. Some of these duplicates have been created even in the same
> day, hour and minute. Other have different creation dates.
> 
> I hope that helps.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/walty8/simple-gmail-notes.chrome/issues/2#issuecomment-173943836
> .

## 

have a nice day
walty

**Comment by allamedo** [comment]
Ok yeah, I removed that note in the third case.

So do you have any idea why I can't see some of the notes in the abstract style?

Have you reproduced the problem?

Cheers.

**Comment by walty8** [comment]
I just spent 30 minutes to do all kinds of experiments on 30+ emails.

I could NOT steadily reproduce the issue, but I did find something strange
from time to time.

I would try to fix this bug by next week.

thanks for the reporting! It's some kind of subtle bug and difficult to be
detected by myself.

On Sat, Jan 23, 2016 at 8:41 PM, pundergit notifications@github.com wrote:

> Ok yeah, I removed that note in the third case.
> 
> So do you have any idea why I can't see some of the notes in the abstract
> style?
> 
> Have you reproduced the problem?
> 
> Cheers.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/walty8/simple-gmail-notes.chrome/issues/2#issuecomment-174183835
> .

## 

have a nice day
walty

**Comment by walty8** [comment]
hi, 

just uploaded version 0.4.3, which fixed two probable places that could cause miss of abstract.

pls have a try and see if the problelm is fixed.

thanks

**Comment by allamedo** [comment]
Hey,

It is working now! Good job man!

Keep it up. This exntesion is really great.

Thank you for your work.

**Comment by walty8** [comment]
that's great :)
